// <auto-generated />
namespace GEC6.Blog.Yan.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StartDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StartDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201703171959424_StartDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
